name       : ncurses
version    : '6.2'
release    : 18
source     :
    - https://ftp.gnu.org/gnu/ncurses/ncurses-6.2.tar.gz : 30306e0c76e0f9f1f0de987cf1c82a5c21e1ce6568b9227f7da5b71cbea86c9d
homepage   : http://www.gnu.org/software/ncurses
license    : GPL-3.0-or-later
component  : system.base
summary    : The ncurses library routines are a terminal-independent method of updating character screens with reasonable optimization.
description: |
    The ncurses library routines are a terminal-independent method of updating character screens with reasonable optimization. This package contains the shared libraries necessary to run programs compiled with ncurses.
devel      : true
autodep    : no
emul32     : yes
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
patterns   :
    - devel :
        - /usr/share/man
environment: |
    # Help with musl builds
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"

    export CXXFLAGS="$CXXFLAGS -std=gnu++98"
setup      : |
    %configure --with-shared \
               --with-normal \
               --without-debug \
               --without-profile \
               --disable-rpath \
               --enable-const \
               --enable-largefile \
               --enable-widec \
               --enable-hard-tabs \
               --enable-xmc-glitch \
               --enable-colorfgbg \
               --with-rcs-ids \
               --with-chtype='long' \
               --with-mmask-t='long' \
               --enable-symlinks \
               --without-gpm \
               --with-manpage-format=gzip \
               --enable-pc-files \
               --with-pkg-config-libdir=%libdir%/pkgconfig \
               --disable-termcap \
               --with-terminfo-dirs='/usr/share/terminfo:/etc/terminfo' \
               --libdir=%libdir% \
               --with-versioned-syms \
               --without-ada
build      : |
    %make
install    : |
    %make_install

    # wide vs non-wide, we'll demote non-wide at some point
    if [[ -z "${EMUL32BUILD}" ]]; then
        for i in ncurses ncursesw ; do
            install -d $installdir/usr/include/${i}
            for j in $installdir/usr/include/*.h ; do
                ln -sv ../$(basename ${j}) $installdir/usr/include/${i}/$(basename ${j})
            done
        done

        # Make these guys visible to musl
        install -D -d -m 00755 $installdir/usr/include/musl
        for i in $installdir/usr/include/*.h ; do
            ln -sv ../$(basename $i) $installdir/usr/include/musl/.
        done

    fi

    # link nonwide..
    for f in $installdir/%libdir%/*w.* ; do
        src=$(basename ${f})
        dst=`echo "$src" | sed 's@w\.@.@g'`
        ln -sv "$src" $installdir/%libdir%/${dst}
    done

    # last compat symlinks
    ln -sv libncurses.so $installdir/%libdir%/libcurses.so
    ln -sv libncurses.a $installdir/%libdir%/libcurses.a
    ln -sv libncursesw.so $installdir/%libdir%/libcursesw.so
    ln -sv libncursesw.a $installdir/%libdir%/libcursesw.a

    ln -sv libncurses.so.6 $installdir/%libdir%/libtinfo.so.6

    # HACK: symlink to old abi version so we can rebuild stuff
    ln -sv libncurses.so.6 $installdir/%libdir%/libncurses.so.5
    ln -sv libncursesw.so.6 $installdir/%libdir%/libncursesw.so.5
    ln -sv libncurses.so.6.2 $installdir/%libdir%/libncurses.so.5.9
    ln -sv libncursesw.so.6.2 $installdir/%libdir%/libncursesw.so.5.9
    ln -sv libform.so.6.2 $installdir/%libdir%/libform.so.5.9
    ln -sv libform.so.6 $installdir/%libdir%/libform.so.5
    ln -sv libpanel.so.6.2 $installdir/%libdir%/libpanel.so.5.9
    ln -sv libpanelw.so.6 $installdir/%libdir%/libpanelw.so.5
    ln -sv libformw.so.6.2 $installdir/%libdir%/libformw.so.5.9
    ln -sv libformw.so.6 $installdir/%libdir%/libformw.so.5
    ln -sv libmenu.so.6.2 $installdir/%libdir%/libmenu.so.5.9
    ln -sv libmenu.so.6 $installdir/%libdir%/libmenu.so.5
    ln -sv libmenuw.so.6.2 $installdir/%libdir%/libmenuw.so.5.9
    ln -sv libmenuw.so.6 $installdir/%libdir%/libmenuw.so.5
