name       : ncurses
version    : 5.9
release    : 7
source     :
    - http://ftp.gnu.org/gnu/ncurses/ncurses-5.9.tar.gz : 9046298fb440324c9d4135ecea7879ffed8546dd1b58e59430ea07a4633f563b
homepage   : http://www.gnu.org/software/ncurses
license    :
    - GPLv3+
summary    : The ncurses library routines are a terminal-independent method of updating
    character screens with reasonable optimization.
description: |
    The ncurses library routines are a terminal-independent method of updating character screens with reasonable optimization. This package contains the shared libraries necessary to run programs compiled with ncurses.
clang      : no
devel      : true
autodep    : no
emul32     : yes
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
setup      : |
    %patch -p1 < $pkgfiles/gcc5.patch
    ./configure --without-debug \
               --without-profile \
               --disable-rpath \
               --enable-const \
               --enable-largefile \
               --enable-widec \
               --with-terminfo-dirs='/usr/share/terminfo:/etc/terminfo' \
               --disable-termcap \
               --enable-hard-tabs \
               --enable-xmc-glitch \
               --enable-colorfgbg \
               --with-shared \
               --with-rcs-ids \
               --with-chtype='long' \
               --with-mmask-t='long' \
               --without-ada \
               --enable-symlinks \
               --without-gpm \
               --mandir=/usr/share/man \
               --libdir=%libdir% \
               --disable-static \
               --enable-pc-files \
               PKG_CONFIG_LIBDIR=%libdir%/pkgconfig
build      : |
    %make
install    : |
    %make_install

    # wide vs non-wide, we'll demote non-wide at some point
    if [[ -z "${EMUL32BUILD}" ]]; then
        for i in ncurses ncursesw ; do
            install -d $installdir/usr/include/${i}
            for j in $installdir/usr/include/*.h ; do
                ln -sv ../$(basename ${j}) $installdir/usr/include/${i}/$(basename ${j})
            done
        done
    fi

    # link nonwide..
    for f in $installdir/%libdir%/*w.* ; do
        src=$(basename ${f})
        dst=`echo "$src" | sed 's@w\.@.@g'`
        ln -sv "$src" $installdir/%libdir%/${dst}
    done

    # last compat symlinks
    ln -sv libncurses.so $installdir/%libdir%/libcurses.so
    ln -sv libncursesw.so $installdir/%libdir%/libcursesw.so
